# Generated by Django 5.2.1 on 2025-06-08 09:29

from django.db import migrations


def seed_moods(apps, schema_editor):
    Mood = apps.get_model("moods", "Mood")
    initial = [
        {"name": "Happy", "emoji": "😊", "category": "positive"},
        {"name": "Laugh", "emoji": "😆", "category": "positive"},
        {"name": "Sad", "emoji": "😢", "category": "negative"},
        {"name": "Anxious", "emoji": "😰", "category": "negative"},
        {"name": "Calm", "emoji": "😌", "category": "neutral"},
    ]

    for mood in initial:
        Mood.objects.update_or_create(name=mood["name"], defaults=mood)


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_moods, reverse_code=migrations.RunPython.noop),
    ]

# This migration seeds the initial moods into the database.
